name: Build and Deploy ReactJS Project with Jekyll to GitHub Pages

on:
  push:
    branches:
      - master # Change this to your main branch name
  pull_request:
    branches:
      - master # Change this to your main branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: Install Dependencies
      run: npm install

    - name: Build React App
      run: npm run build

    - name: Copy built files to Jekyll directory
      run: cp -a build/. docs/

    - name: Build Jekyll Site
      uses: actions/checkout@v2
      with:
        submodules: true
    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@4.1.2
      with:
        ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: docs # Change this if your Jekyll site is built to a different folder
        CLEAN: true
